[package]
name = "vim-pandoc-syntax"
version = "0.0.0"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = "0.7.1"
mlua = { version = "0.3.2", default-features = false, features = [ "luajit" ] }
mlua_derive = "0.3.0"
